### PR TITLE
fix(pwg): stall instead of fail for unassigned black box

### LINKED ISSUE #153: Solving fails when encountering a blackbox with unassigned inputs
### Aim

Fix ACVM's broken partial witness solving.

### Expected behavior

All of `noir/crates/nargo/tests/test_data` should pass, but `6_array` fails.

### Bug

If the ACVM encounters a back box call for which the inputs haven't yet been assigned, it exits prematurely with `OpcodeNotSolvable::MissingAssignment`.

### To reproduce

1. Upgrade noir to use ACVM 0.7.0
2. run `cargo test`

### Versions

ACVM 0.7.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by joss-aztec**
inputs

# Related issue(s)

Resolves #153

# Description

## Summary of changes

Stall instead of fail when encountering black box function inputs.

# Checklist

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [x] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [x] I have reviewed the changes on GitHub, line by line.
- [x] I have ensured all changes are covered in the description.

### CODE REVIEW

File: acvm/src/lib.rs [hunk 1]
```diff
@@ -157,14 +165,18 @@ pub trait PartialWitnessGenerator {
...
-    fn all_func_inputs_assigned(
+    // Returns the first missing assignment if any are missing
+    fn first_missing_assignment(
         initial_witness: &mut BTreeMap<Witness, FieldElement>,
         func_call: &BlackBoxFuncCall,
-    ) -> bool {
-        // This call to .any returns true, if any of the witnesses do not have assignments
-        // We then use `!`, so it returns false if any of the witnesses do not have assignments
-        !func_call.inputs.iter().any(|input| !initial_witness.contains_key(&input.witness))
+    ) -> Option<u32> {
```
Comment (kevaundray) [inline acvm/src/lib.rs:172]: `return Option<Witness>`

**Review by kevaundray — APPROVED** [review]
