### PR TITLE
fix: Clean up Log Directive hex output 

### LINKED ISSUE #94: Have Directive::Log output format match println eval in acir gen
# Description

There were some changes to the print formatting when making this println statements PR on Noir: https://github.com/noir-lang/noir/pull/630.

## Aim

There are some Logs that require witness information that can only be fetched during solving of the witness. The directive had to be made before making changes to Noir so that Noir could access `Directive::Log` during acir gen. During PR review of https://github.com/noir-lang/noir/pull/630 some of the print formatting changed. We should bring `Directive::Log` up to speed.  

## Expected behavior

That hex output for printing during acir gen and when we solve the witness should match.

## Bug

The output during witness solving is outdated.

# To reproduce

If you try and log values that requires solving the witness you will see the difference.

1.
2.
3.
4.

# Environment

(Specify your setup and versions of dependencies.)

- OS:

For `nargo` users

- _noir-lang/noir_ commit cloned:
- Proving backend
  - [ ] default
    - Clang: (run `clang --version`)
  - [ ] wasm-base

For TypeScript users

- Node.js: (run `node --version`)
- @noir-lang/noir_wasm: (from `yarn.lock`)
- @noir-lang/barretenberg: (from `yarn.lock`)
- @noir-lang/aztec_backend: (from `yarn.lock`)

# Additional context

(If applicable.)

### PR DESCRIPTION
**Pull request by vezenovm**
# Related issue(s)

Resolves #94 

## Summary of changes

We just now trim the zeroes for hex output. 

## Dependency additions / changes

(If applicable.)

## Test additions / changes

I have seen the result of this output when testing the println PR on the Noir repo. 

# Checklist

- [X] I have tested the changes locally.
- [X] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` with default settings.
- [X] I have [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) this PR to the issue(s) that it resolves.
- [X] I have reviewed the changes on GitHub, line by line.
- [X] I have ensured all changes are covered in the description.

# Additional context

(If applicable.)

### CODE REVIEW

**Review by TomAFrench — APPROVED** [review]

File: acvm/src/pwg/directives.rs [hunk 1]
```diff
@@ -228,3 +228,15 @@ fn insert_witness(
...
+
+/// This trims any leading zeroes.
+/// A singular '0' will be prepended as well if the trimmed string has an odd length.
+/// A hex string's length needs to be even to decode into bytes, as two digits correspond to
+/// one byte.
+fn format_field_string(field: FieldElement) -> String {
+    let mut trimmed_field = field.to_hex().trim_start_matches('0').to_owned();
+    if trimmed_field.len() % 2 != 0 {
+        trimmed_field = "0".to_owned() + &trimmed_field
+    };
```
Comment (jfecher) [inline acvm/src/pwg/directives.rs:240]: Unnecessay `;`
